// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByRG3s7Uqsk_ngdLY0KqloGYcVfkgwWd4',
    appId: '1:635290938955:web:83580767ddaec05d63e7ce',
    messagingSenderId: '635290938955',
    projectId: 'gocart-b0866',
    authDomain: 'gocart-b0866.firebaseapp.com',
    storageBucket: 'gocart-b0866.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_-4WAQqyiKiJo1QvECeq6noDYNN6vjB0',
    appId: '1:635290938955:android:b71e57749336abd963e7ce',
    messagingSenderId: '635290938955',
    projectId: 'gocart-b0866',
    storageBucket: 'gocart-b0866.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDadutstDtoQxyVFEShSYVVaOjsZbT_K-c',
    appId: '1:635290938955:ios:b431042121ad817863e7ce',
    messagingSenderId: '635290938955',
    projectId: 'gocart-b0866',
    storageBucket: 'gocart-b0866.firebasestorage.app',
    iosBundleId: 'com.example.gocart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDadutstDtoQxyVFEShSYVVaOjsZbT_K-c',
    appId: '1:635290938955:ios:b431042121ad817863e7ce',
    messagingSenderId: '635290938955',
    projectId: 'gocart-b0866',
    storageBucket: 'gocart-b0866.firebasestorage.app',
    iosBundleId: 'com.example.gocart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByRG3s7Uqsk_ngdLY0KqloGYcVfkgwWd4',
    appId: '1:635290938955:web:25f96f2cfe3d2cae63e7ce',
    messagingSenderId: '635290938955',
    projectId: 'gocart-b0866',
    authDomain: 'gocart-b0866.firebaseapp.com',
    storageBucket: 'gocart-b0866.firebasestorage.app',
  );
}
